let lang='zh',currentSlide=0,paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches,timer;
const $$=(selector)=>[...document.querySelectorAll(selector)];
function setLanguage(value){lang=value;document.documentElement.lang=value==='zh'?'zh-CN':'en';$$('[data-zh]').forEach(el=>el.textContent=el.dataset[value]);$$('[data-alt-zh]').forEach(el=>el.alt=el.dataset[value==='zh'?'altZh':'altEn']);$$('[data-lang]').forEach(el=>{el.classList.toggle('active',el.dataset.lang===value);el.setAttribute('aria-pressed',String(el.dataset.lang===value))});document.title=document.body.dataset[value==='zh'?'titleZh':'titleEn']||(value==='zh'?'tii | 以创新连接产业，以品质改善生活':'tii | Connecting Innovation, Enriching Life');document.querySelector('meta[name="description"]').content=value==='zh'?'TRINITY INDUSTRIAL & INVESTMENT GROUP PTE. LTD. — 农业化学品、医疗器械、大宗商品贸易、国际运输与海外仓储。':'TRINITY INDUSTRIAL & INVESTMENT GROUP PTE. LTD. — Agriculture, medical devices, commodity trading, international transportation and overseas warehousing.';document.querySelector('nav').setAttribute('aria-label',value==='zh'?'主导航':'Main navigation');document.querySelector('.hero')?.setAttribute('aria-label',value==='zh'?'四大业务':'Our four business divisions');document.querySelector('#previous')?.setAttribute('aria-label',value==='zh'?'上一张':'Previous slide');document.querySelector('#next')?.setAttribute('aria-label',value==='zh'?'下一张':'Next slide');updatePause();updateMenu();try{localStorage.setItem('tii-language',value)}catch{} }
function updatePause(){const p=document.querySelector('#pause');if(!p)return;p.textContent=paused?'▷':'Ⅱ';p.setAttribute('aria-label',lang==='zh'?(paused?'开始自动轮播':'暂停自动轮播'):(paused?'Start slideshow':'Pause slideshow'));p.setAttribute('aria-pressed',String(paused))}
function showSlide(index){currentSlide=(index+4)%4;$$('.slide').forEach((slide,i)=>{slide.classList.toggle('active',i===currentSlide);slide.setAttribute('aria-hidden',String(i!==currentSlide));slide.inert=i!==currentSlide});$$('[data-go]').forEach((el,i)=>{el.classList.toggle('active',i===currentSlide);el.setAttribute('aria-pressed',String(i===currentSlide))})}
function startTimer(){clearInterval(timer);if(document.querySelector('.hero')&&!paused&&!document.hidden)timer=setInterval(()=>showSlide(currentSlide+1),6500)}
function manualSlide(index){showSlide(index);startTimer()}
$$('[data-lang]').forEach(el=>el.addEventListener('click',()=>setLanguage(el.dataset.lang)));
$$('[data-go]').forEach(el=>el.addEventListener('click',()=>manualSlide(Number(el.dataset.go))));
document.querySelector('#next')?.addEventListener('click',()=>manualSlide(currentSlide+1));document.querySelector('#previous')?.addEventListener('click',()=>manualSlide(currentSlide-1));document.querySelector('#pause')?.addEventListener('click',()=>{paused=!paused;updatePause();startTimer()});
const hero=document.querySelector('.hero');hero?.addEventListener('mouseenter',()=>clearInterval(timer));hero?.addEventListener('mouseleave',startTimer);hero?.addEventListener('focusin',()=>clearInterval(timer));hero?.addEventListener('focusout',(e)=>{if(!hero.contains(e.relatedTarget))startTimer()});hero?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();manualSlide(currentSlide+(e.key==='ArrowRight'?1:-1))}});let touchX=0;hero?.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX},{passive:true});hero?.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-touchX;if(Math.abs(delta)>60)manualSlide(currentSlide+(delta<0?1:-1))},{passive:true});document.addEventListener('visibilitychange',startTimer);
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');function updateMenu(){menu.setAttribute('aria-label',lang==='zh'?(nav.classList.contains('open')?'关闭菜单':'打开菜单'):(nav.classList.contains('open')?'Close menu':'Open menu'))}function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');updateMenu()}menu.addEventListener('click',()=>{const opened=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(opened));updateMenu()});$$('nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelector('#year').textContent=new Date().getFullYear();try{lang=localStorage.getItem('tii-language')==='en'?'en':'zh'}catch{}setLanguage(lang);startTimer();
